GET http://localhost:5000/users

###
GET http://localhost:5000/users/68a1b22c0856061fa6ca6503

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Sahira",
    "email": "clairedelune@gmail.com",
    "gender": "female"

}

###
PATCH   http://localhost:5000/users/68a1b22c0856061fa6ca6503
Content-Type: application/json

{
    "name": "Syakilla",
    "email": "Syakillaputri@gmail.com",
    "gender": "female"

}

###
DELETE  http://localhost:5000/users/68a1b22c0856061fa6ca6503
Content-Type: application/json

{
    "name": "Syakilla",
    "email": "Syakillaputri@gmail.com",
    "gender": "female"

}
